language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - flake8 .
  - pylint log worker task linked_list linked_list_item paymentperhour fixedpayment
  - mypy --ignore-missing-imports .
