language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - flake8 .
  - pylint test_module task hourly fixed worker log
  - mypy --ignore-missing-imports .
