language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - flake8 .
  - pylint test_modules.py
  - pylint log.py
  - pylint tasks.py
  - pylint day_plan.py
  - pylint worker.py
  - mypy --ignore-missing-imports .
